import { useEffect } from "react";
import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";

export function PrivacyPage() {
  useEffect(() => {
    window.scrollTo(0, 0);
    document.title = "Privacy Policy — GSM World";
  }, []);

  const Section = ({ n, title, children }: { n: number; title: string; children: string }) => (
    <section className="pb-3 border-b border-border/40 last:border-0">
      <h2 className="text-[13px] font-bold text-foreground mb-1">{n}. {title}</h2>
      <p className="text-[13px] text-muted-foreground leading-relaxed">{children}</p>
    </section>
  );

  return (
    <div className="max-w-3xl mx-auto px-4 py-8 pb-20">
      <div className="mb-6">
        <Link href="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft size={15} />
          Back to Home
        </Link>
      </div>

      <div className="space-y-6">
        <div>
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-widest mb-2">Legal</p>
          <h1 className="text-3xl font-black text-foreground mb-1">Privacy Policy</h1>
          <p className="text-sm text-muted-foreground">GSM World · Effective Date: 1 June 2025 · Last Updated: 1 June 2025</p>
        </div>

        <div className="space-y-4">
          <Section n={1} title="Introduction">GSM World ("we", "our", or "us") is committed to protecting your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your data when you use our platform, website, and related services.</Section>
          <Section n={2} title="Acceptance of This Policy">By accessing or using the Service, you confirm that you have read, understood, and agree to be bound by this Privacy Policy. If you do not agree, please discontinue use immediately.</Section>
          <Section n={3} title="Scope of This Policy">This policy applies to all data collected through our website, mobile application, APIs, customer support channels, and any other interaction you have with GSM World.</Section>
          <Section n={4} title="Controller Identity">GSM World acts as the data controller for personal data collected through the Service. Contact us via the support email with any privacy-related inquiries.</Section>
          <Section n={5} title="Definitions">"Personal Data" means any information relating to an identified or identifiable natural person. "Processing" means any operation performed on Personal Data. "Service" means the GSM World platform and all related services.</Section>
          <Section n={6} title="Data We Collect — Account Information">When you create an account, we collect your full name, email address, phone number, and a hashed version of your password. We do not store passwords in plain text under any circumstances.</Section>
          <Section n={7} title="Data We Collect — Order Information">We collect device identifiers submitted with service requests (IMEI numbers, serial numbers), order details, service types selected, and the complete status history of each order.</Section>
          <Section n={8} title="Data We Collect — Payment Information">We collect transaction references, payment method types, and confirmation details. We do not store full payment card numbers, M-Pesa PINs, or cryptocurrency private keys on our servers.</Section>
          <Section n={9} title="Data We Collect — Usage Data">We automatically collect IP addresses, browser type and version, operating system, pages visited, time spent on pages, referring URLs, and session identifiers during your use of the Service.</Section>
          <Section n={10} title="Data We Collect — Device Data">We may collect information about the device you use to access the Service, including hardware model, operating system version, unique device identifiers, and mobile network information.</Section>
          <Section n={11} title="Data We Collect — Communications">We retain records of messages sent through our in-app live chat, support email correspondence, and any files or screenshots you upload through the platform for support purposes.</Section>
          <Section n={12} title="Data We Collect — Location Data">We may infer approximate location from your IP address for fraud prevention and service eligibility purposes. We do not collect precise GPS location data unless you explicitly grant such permission.</Section>
          <Section n={13} title="Data We Collect — Financial Transactions">We maintain records of wallet top-ups, service purchases, refunds, and full transaction histories necessary for accounting, customer support, and dispute resolution purposes.</Section>
          <Section n={14} title="Data We Collect — Reseller Information">If you use our reseller program, we collect business name, reseller tier, pricing configurations, and sub-user account data associated with your reseller profile.</Section>
          <Section n={15} title="Data We Collect — Referral and Promotion Data">If you participate in promotional programs, we collect referral codes used, promotional credits applied, and the identity of referring users where applicable to administer the program.</Section>
          <Section n={16} title="Data We Collect — Survey and Feedback Data">If you participate in surveys, submit ratings, or provide feedback, we collect your responses and may associate them with your account for service improvement purposes.</Section>
          <Section n={17} title="Data We Collect — Technical Error Reports">Error logs, crash reports, and technical diagnostics may be collected automatically to identify and resolve platform issues. These logs may include partial session and device information.</Section>
          <Section n={18} title="How We Use Data — Service Delivery">We use your data to fulfill orders, process payments, deliver digital services, issue unlock codes, and communicate order status updates to you in a timely manner.</Section>
          <Section n={19} title="How We Use Data — Account Management">We use your data to create and maintain your account, authenticate your identity, allow password reset, issue authentication tokens, and manage session security.</Section>
          <Section n={20} title="How We Use Data — Customer Support">We use your personal data and order history to respond to support requests, investigate complaints, resolve disputes, and improve our overall service quality.</Section>
          <Section n={21} title="How We Use Data — Fraud Prevention">We analyze usage patterns, payment data, and account activity to detect and prevent fraudulent transactions, unauthorized access, account takeovers, and abuse of our platform.</Section>
          <Section n={22} title="How We Use Data — Legal Compliance">We process data where necessary to comply with applicable laws, respond to legal process, enforce our terms, and protect the rights and safety of our users and third parties.</Section>
          <Section n={23} title="How We Use Data — Service Improvement">Aggregated, anonymized usage data helps us understand how users interact with the Service, identify performance bottlenecks, and prioritize feature development and improvements.</Section>
          <Section n={24} title="How We Use Data — Communications and Notifications">We send transactional emails (order confirmations, payment receipts, status updates) and, where you have opted in, promotional communications about new services and offers.</Section>
          <Section n={25} title="How We Use Data — Personalization">We may use your order history and usage patterns to display relevant products, suggest services you may find useful, and personalize your experience on the platform.</Section>
          <Section n={26} title="How We Use Data — AI-Powered Features">If you interact with our AI assistant, your messages are processed to generate responses. Conversation data may be retained to improve our AI models. We do not sell this data to third parties.</Section>
          <Section n={27} title="How We Use Data — Platform Security">We use data to monitor for unauthorized access attempts, enforce rate limits, detect bot activity, and maintain the security and integrity of our platform infrastructure.</Section>
          <Section n={28} title="Legal Basis — Contractual Necessity">Much of our data processing is necessary to perform the contract between you and GSM World — including fulfilling orders, managing your account, and processing payments you have initiated.</Section>
          <Section n={29} title="Legal Basis — Legitimate Interests">We process data for legitimate business interests including fraud prevention, security monitoring, analytics, and improving our services, where these interests are not overridden by your privacy rights.</Section>
          <Section n={30} title="Legal Basis — Legal Obligation">We process data where we have a legal obligation to do so, such as retaining financial records for tax purposes or responding to lawful requests from law enforcement authorities.</Section>
          <Section n={31} title="Legal Basis — Consent">Where required by law, we obtain your consent before processing your data for specific purposes such as marketing communications. You may withdraw consent at any time without penalty.</Section>
          <Section n={32} title="Data Sharing — Service Providers">We share data with trusted third-party service providers who process it on our behalf, including payment processors, email delivery services, cloud infrastructure providers, and analytics tools.</Section>
          <Section n={33} title="Data Sharing — Payment Processors">Transactions are processed by third-party payment providers (M-Pesa, Stripe, cryptocurrency networks). These providers have their own privacy policies governing the data they collect and process.</Section>
          <Section n={34} title="Data Sharing — Unlock Service Providers">To deliver unlock services, we share device identifiers (IMEI, serial numbers) with our network of unlock service suppliers, strictly limited to what is necessary for service delivery.</Section>
          <Section n={35} title="Data Sharing — Legal Disclosures">We may disclose your data to law enforcement, courts, or regulatory authorities when required by law, court order, or where we believe disclosure is necessary to prevent serious harm.</Section>
          <Section n={36} title="Data Sharing — Business Transfers">In the event of a merger, acquisition, or sale of all or part of our business, your personal data may be transferred to the acquiring entity, subject to equivalent privacy protections.</Section>
          <Section n={37} title="Data Sharing — Aggregated Data">We may share aggregated, anonymized data that cannot reasonably identify you with third parties for research, industry analysis, reporting, or marketing purposes.</Section>
          <Section n={38} title="Data Sharing — With Your Consent">We will share your personal data with third parties outside the above categories only where you have given explicit, informed consent to such sharing.</Section>
          <Section n={39} title="No Sale of Personal Data">GSM World does not sell, rent, or trade your personal data to third parties for their own marketing purposes. Your data is used solely to provide and improve our services to you.</Section>
          <Section n={40} title="Data Security — Technical Measures">We implement industry-standard security measures including TLS/HTTPS encryption for data in transit, hashed password storage, and strict access controls to protect your personal data.</Section>
          <Section n={41} title="Data Security — Organizational Measures">Access to personal data is restricted to authorized personnel on a need-to-know basis. We conduct regular security reviews, training, and maintain incident response procedures.</Section>
          <Section n={42} title="Data Security — Authentication">We support two-factor authentication (2FA) via TOTP apps for user accounts, and biometric/WebAuthn authentication for admin access to add extra layers of account security.</Section>
          <Section n={43} title="Data Security — Infrastructure">We use reputable cloud infrastructure providers that maintain their own security certifications. Our infrastructure is regularly updated to address security vulnerabilities.</Section>
          <Section n={44} title="Data Security — Breach Notification">In the event of a data breach likely to risk your rights and freedoms, we will notify affected users and, where required, relevant supervisory authorities without undue delay.</Section>
          <Section n={45} title="Data Security — No Absolute Guarantee">While we implement robust security measures, no method of transmission over the internet or electronic storage is 100% secure. We cannot guarantee absolute security of your data.</Section>
          <Section n={46} title="Data Retention — General Principle">We retain personal data only for as long as necessary to fulfill the purposes for which it was collected, comply with legal obligations, resolve disputes, and enforce our agreements.</Section>
          <Section n={47} title="Data Retention — Account Data">Account data is retained for the duration of your account and for a reasonable period thereafter to allow for dispute resolution and legal compliance. You may request deletion at any time.</Section>
          <Section n={48} title="Data Retention — Transaction Records">Financial transaction records are retained for a minimum period as required by applicable tax and accounting laws, typically seven years in most jurisdictions where we operate.</Section>
          <Section n={49} title="Data Retention — Support Communications">Support tickets and related communications are retained for up to three years to assist with future support requests, quality assurance, and audit purposes.</Section>
          <Section n={50} title="Data Retention — Log Data">Server access logs and security logs are typically retained for 90 days unless a security incident or legal obligation requires longer retention for investigation purposes.</Section>
          <Section n={51} title="Your Rights — Right of Access">You have the right to request a copy of the personal data we hold about you. We will provide this within 30 days of a verified request, free of charge for the first request per year.</Section>
          <Section n={52} title="Your Rights — Right to Rectification">You have the right to request correction of any inaccurate or incomplete personal data we hold. You may update most account data directly within your account settings without contacting us.</Section>
          <Section n={53} title="Your Rights — Right to Erasure">You have the right to request deletion of your personal data where there is no compelling reason for continued processing. We will honor such requests subject to our legal retention obligations.</Section>
          <Section n={54} title="Your Rights — Right to Restrict Processing">You have the right to request that we restrict processing of your data in certain circumstances, such as when you contest its accuracy or object to our basis for processing it.</Section>
          <Section n={55} title="Your Rights — Right to Data Portability">Where technically feasible, you have the right to receive your personal data in a structured, commonly used, machine-readable format and to transmit it to another controller of your choosing.</Section>
          <Section n={56} title="Your Rights — Right to Object">You have the right to object to processing of your data based on legitimate interests or for direct marketing purposes. We will cease processing unless we have compelling legitimate grounds.</Section>
          <Section n={57} title="Your Rights — Automated Decision-Making">You have the right not to be subject to decisions based solely on automated processing, including profiling, that produce legal or similarly significant effects on your account or access.</Section>
          <Section n={58} title="Your Rights — How to Exercise Them">To exercise any of these rights, contact us via the support email. We may require identity verification before processing your request to protect against unauthorized access to your data.</Section>
          <Section n={59} title="Your Rights — Response Timeframes">We aim to respond to all rights requests within 30 days. In complex cases, we may extend this by a further two months, in which case we will notify you of the extension and the reasons.</Section>
          <Section n={60} title="Your Rights — No Fee for Requests">Exercising your data rights is free of charge. We reserve the right to charge a reasonable fee or refuse to act on requests that are manifestly unfounded, excessive, or repetitive.</Section>
          <Section n={61} title="Cookies — What Are Cookies">Cookies are small text files placed on your device by websites you visit. They are widely used to make websites work efficiently and to provide useful information to site owners.</Section>
          <Section n={62} title="Cookies — Strictly Necessary">We use strictly necessary cookies to operate the Service, including session authentication tokens and security cookies. These cannot be disabled as the Service cannot function without them.</Section>
          <Section n={63} title="Cookies — Functional Cookies">Functional cookies remember your preferences (such as language and display settings) to provide a more personalized experience. You may disable these without affecting core platform functionality.</Section>
          <Section n={64} title="Cookies — Analytics Cookies">We may use analytics tools that place cookies to help us understand how users interact with the Service. This data is aggregated and used only for service improvement purposes, not profiling.</Section>
          <Section n={65} title="Cookies — Local Storage">In addition to cookies, we use browser local storage to persist your authentication state, user preferences, and shopping cart contents between sessions for your convenience.</Section>
          <Section n={66} title="Cookies — Managing Cookies">You can control cookies through your browser settings. Disabling certain cookies may impair Service functionality. Clearing local storage will log you out and reset your preferences.</Section>
          <Section n={67} title="Cookies — Third-Party Cookies">Some third-party services embedded in our platform (such as payment widgets) may set their own cookies. We do not control these and recommend reviewing the relevant third-party privacy policies.</Section>
          <Section n={68} title="Payment Data — Security Standards">Payment processing is handled by PCI-DSS compliant third-party providers. We do not store full card numbers on our servers. All payment data in transit is encrypted using TLS.</Section>
          <Section n={69} title="Payment Data — M-Pesa">For M-Pesa payments, we collect your phone number and transaction confirmation codes. M-Pesa PINs are entered directly on the Safaricom interface and are never transmitted to or stored by GSM World.</Section>
          <Section n={70} title="Payment Data — Cryptocurrency">For crypto payments, we record wallet addresses, transaction hashes, and amounts for verification purposes. Cryptocurrency private keys are never shared with or accessible to GSM World.</Section>
          <Section n={71} title="Payment Data — Stripe Payments">Card payments are processed by Stripe, Inc. Stripe's privacy policy governs the handling of your card data. We receive only tokenized representations and transaction outcome data from Stripe.</Section>
          <Section n={72} title="Payment Data — Refund Records">Refund requests and processing records are retained as part of your transaction history and are used for accounting, dispute resolution, and regulatory compliance purposes.</Section>
          <Section n={73} title="IMEI and Device Data — Use">IMEI numbers and device identifiers submitted for unlock services are used solely for service delivery and necessary API calls to unlock service providers. No other use is made of this data.</Section>
          <Section n={74} title="IMEI and Device Data — Sharing">IMEI data is shared only with the specific unlock service provider required to fulfill your order. We do not share IMEIs with unrelated third parties or use them for any secondary purpose.</Section>
          <Section n={75} title="IMEI and Device Data — Retention">IMEI data is retained as part of your order record for the duration specified in our data retention policy. You may request deletion subject to our obligations to maintain complete transaction records.</Section>
          <Section n={76} title="Children's Privacy">The Service is not directed to children under the age of 18. We do not knowingly collect personal data from minors. If you believe we have inadvertently collected such data, please contact us for immediate removal.</Section>
          <Section n={77} title="International Data Transfers">Your data may be processed in countries outside your home country, including countries that may not have the same level of data protection law. We implement appropriate safeguards for all international transfers.</Section>
          <Section n={78} title="Standard Contractual Clauses">Where data is transferred internationally, we rely on recognized transfer mechanisms such as Standard Contractual Clauses approved by relevant data protection authorities to provide adequate protections.</Section>
          <Section n={79} title="Third-Party Links">Our Service may contain links to third-party websites. We are not responsible for the privacy practices of those sites and encourage you to review their privacy policies independently before providing any personal data.</Section>
          <Section n={80} title="Third-Party APIs">We use third-party APIs to power certain features (IMEI checking, AI assistance, SMS notifications). Data shared with these services is limited to what is strictly required to deliver the specific feature.</Section>
          <Section n={81} title="Google Authentication">If you sign in using Google, we receive your name, email address, and profile picture from Google. Google's Privacy Policy governs the data Google collects during the authentication process.</Section>
          <Section n={82} title="AI Chat Data">Conversations with our AI assistant may be processed by third-party AI API providers. We implement data minimization principles and do not include unnecessary personal data in AI API requests.</Section>
          <Section n={83} title="SMS Notifications">If you provide a phone number and opt into SMS notifications, your number is shared with our SMS delivery provider solely for the purpose of sending you authorized order or service alerts.</Section>
          <Section n={84} title="Email Communications">We send transactional emails for order confirmations, payment instructions, and account security. You may opt out of marketing emails at any time via the unsubscribe link included in each marketing email.</Section>
          <Section n={85} title="Marketing Communications">We may send marketing emails about new services, promotions, and industry news to users who have opted in. You may unsubscribe at any time without affecting the receipt of essential transactional emails.</Section>
          <Section n={86} title="Do Not Track Signals">Some browsers transmit "Do Not Track" signals. Our current platform does not respond differently to Do Not Track signals, but we respect your choices regarding cookies as set out in Section 62–66.</Section>
          <Section n={87} title="California Privacy Rights (CCPA)">California residents have specific rights under the California Consumer Privacy Act, including the right to know, delete, and opt out of the sale of personal information. GSM World does not sell personal information.</Section>
          <Section n={88} title="European Privacy Rights (GDPR)">If you are located in the European Economic Area, you have rights under the GDPR including access, rectification, erasure, portability, and the right to lodge a complaint with a supervisory authority.</Section>
          <Section n={89} title="UK Privacy Rights">Users in the United Kingdom are protected under the UK GDPR and the Data Protection Act 2018. The UK Information Commissioner's Office (ICO) is the supervisory authority for UK residents.</Section>
          <Section n={90} title="African Data Protection">We comply with applicable data protection laws in African jurisdictions where we operate, including the Kenya Data Protection Act, 2019, and equivalent legislation in other applicable territories.</Section>
          <Section n={91} title="Data Minimization">We adhere to the principle of data minimization, collecting only the personal data that is strictly necessary for the specific, stated purposes described in this Privacy Policy.</Section>
          <Section n={92} title="Purpose Limitation">We will not process your personal data for purposes that are incompatible with those for which it was originally collected, unless we obtain your consent or have an independent lawful basis to do so.</Section>
          <Section n={93} title="Storage Limitation">We will not retain personal data in identifiable form for longer than necessary for its stated purposes. Data is securely deleted or anonymized when the applicable retention period expires.</Section>
          <Section n={94} title="Accuracy">We take reasonable steps to ensure that personal data we hold is accurate and up to date. Please update your account information when your details change, or contact us to request correction of inaccuracies.</Section>
          <Section n={95} title="Privacy by Design">Privacy considerations are embedded in our product development process. We assess the privacy implications of new features before deployment and implement technical measures to protect your data by default.</Section>
          <Section n={96} title="Wallet and Credit Data">Your wallet balance and credit history are visible only to you and authorized GSM World staff. This data is used solely for facilitating service purchases and maintaining accurate account records.</Section>
          <Section n={97} title="Reseller Data Processing">Resellers who use our platform are responsible for their own compliance with data protection laws when processing the data of their end customers. GSM World acts as a data processor in this context under appropriate data processing agreements.</Section>
          <Section n={98} title="Automated Decision-Making in Fraud Prevention">We may use automated systems to detect fraud or abuse. If an automated decision significantly affects your account, you have the right to request human review and to contest the decision with supporting information.</Section>
          <Section n={99} title="Complaints and Supervisory Authority">If you believe we have not handled your personal data in accordance with this policy, you have the right to lodge a complaint with the relevant data protection supervisory authority in your jurisdiction.</Section>
          <Section n={100} title="Security Incident Response">In the event of a confirmed data breach that poses a risk to individuals, we will notify affected users by email and, where required, relevant supervisory authorities within legally mandated timeframes.</Section>
          <Section n={101} title="Updates to This Policy">We may update this Privacy Policy from time to time to reflect changes in our practices, technology, or legal requirements. We will notify you of material changes by email or prominent notice on the Service.</Section>
          <Section n={102} title="Continued Use After Changes">Your continued use of the Service after the effective date of a revised Privacy Policy constitutes your acceptance of the updated terms. If you disagree with changes, please discontinue use and contact us to close your account.</Section>
          <Section n={103} title="Contact Us">For privacy-related inquiries, data subject requests, or to report a privacy concern, please contact GSM World via the support email address listed on our Contact Us page. We aim to respond within 30 days.</Section>
          <Section n={104} title="Language">This Privacy Policy is written in English. Any translation provided is for convenience only. In the event of any discrepancy between versions, the English version controls in all cases.</Section>
          <Section n={105} title="Severability">If any provision of this Privacy Policy is found to be invalid or unenforceable under applicable law, the remaining provisions shall continue in full force and effect without modification.</Section>
          <Section n={106} title="Entire Agreement">This Privacy Policy, together with our Terms and Conditions, constitutes the entire agreement between you and GSM World with respect to privacy and personal data processing.</Section>
          <Section n={107} title="Waiver">Failure by GSM World to enforce any provision of this Privacy Policy on any occasion shall not constitute a waiver of that provision or of our right to enforce it on any subsequent occasion.</Section>
          <Section n={108} title="Governing Law">This Privacy Policy shall be governed by and construed in accordance with applicable laws of the jurisdiction in which GSM World is registered, without regard to conflict of law principles.</Section>
          <Section n={109} title="Third-Party Beneficiaries">This Privacy Policy does not create any third-party beneficiary rights. Only you and GSM World have rights and obligations under this policy.</Section>
          <Section n={110} title="Acknowledgment">By using our Service, you acknowledge that you have read and understood this Privacy Policy and agree to the collection, use, and disclosure of your personal data as described herein.</Section>
        </div>
      </div>
    </div>
  );
}
