import { useEffect } from "react";
import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";

export function TermsPage() {
  useEffect(() => {
    window.scrollTo(0, 0);
    document.title = "Terms & Conditions — GSM World";
  }, []);

  const Section = ({ n, title, children }: { n: number; title: string; children: string }) => (
    <section className="pb-3 border-b border-border/40 last:border-0">
      <h2 className="text-[13px] font-bold text-foreground mb-1">{n}. {title}</h2>
      <p className="text-[13px] text-muted-foreground leading-relaxed">{children}</p>
    </section>
  );

  return (
    <div className="max-w-3xl mx-auto px-4 py-8 pb-20">
      <div className="mb-6">
        <Link href="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft size={15} />
          Back to Home
        </Link>
      </div>

      <div className="space-y-6">
        <div>
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-widest mb-2">Legal</p>
          <h1 className="text-3xl font-black text-foreground mb-1">Terms &amp; Conditions</h1>
          <p className="text-sm text-muted-foreground">GSM World · Effective Date: 1 June 2025 · Last Updated: 1 June 2025</p>
        </div>

        <div className="space-y-4">
          <Section n={1} title="Agreement to Terms">By accessing or using the GSM World platform, website, or any related services (collectively, the "Service"), you agree to be bound by these Terms and Conditions ("Terms"). If you do not agree, do not use the Service.</Section>
          <Section n={2} title="Who We Are">GSM World is a digital services platform providing device unlocking, IMEI-based services, and related products to consumers and business resellers globally. Our platform is operated by the GSM World team.</Section>
          <Section n={3} title="Eligibility">You must be at least 18 years of age and have the legal capacity to enter into binding contracts to use the Service. By using the Service, you represent that you meet these requirements.</Section>
          <Section n={4} title="Account Registration">To access most features of the Service, you must create an account by providing accurate, current, and complete information. You are responsible for maintaining the confidentiality of your login credentials.</Section>
          <Section n={5} title="Account Accuracy">You agree to keep your account information accurate and up to date. Providing false, misleading, or fraudulent information is a violation of these Terms and may result in immediate account termination.</Section>
          <Section n={6} title="Account Security">You are solely responsible for all activity that occurs under your account. You must notify us immediately of any unauthorized access to or use of your account at support@gsmworld.com.</Section>
          <Section n={7} title="One Account Per User">You may maintain only one personal account. Creating multiple accounts to circumvent restrictions, obtain promotional credits, or evade suspensions is strictly prohibited and will result in termination of all accounts.</Section>
          <Section n={8} title="Account Termination by You">You may close your account at any time by contacting our support team. Closing your account does not entitle you to a refund of any wallet balance unless otherwise stated in our Refund Policy.</Section>
          <Section n={9} title="Account Termination by Us">We reserve the right to suspend or terminate your account at any time, with or without notice, for any violation of these Terms, suspected fraud, abuse, or for any other reason in our sole discretion.</Section>
          <Section n={10} title="Effect of Termination">Upon termination, your right to access the Service ceases immediately. We may retain your data as required by law or our data retention policy. Provisions that by their nature survive termination shall remain in effect.</Section>
          <Section n={11} title="Description of Services">GSM World provides device unlock services (network unlocks, SIM unlocks, carrier unlocks), IMEI-based services (blacklist check, warranty check, carrier check), and related digital products.</Section>
          <Section n={12} title="Service Availability">We strive to provide uninterrupted access to the Service but do not guarantee 100% uptime. The Service may be unavailable for scheduled maintenance, emergency repairs, or reasons beyond our control.</Section>
          <Section n={13} title="Service Changes">We reserve the right to modify, suspend, or discontinue any part of the Service at any time without notice. We are not liable to you or any third party for any such modification, suspension, or discontinuation.</Section>
          <Section n={14} title="Service Accuracy">While we make every effort to ensure service information is accurate, we do not warrant that product descriptions, pricing, availability, or other information on the platform is complete, reliable, or error-free.</Section>
          <Section n={15} title="Third-Party Service Providers">Many of our services are fulfilled through third-party unlock providers. GSM World acts as an intermediary and cannot guarantee the timeline or outcome of services provided by third parties.</Section>
          <Section n={16} title="Turnaround Times">Estimated turnaround times provided for unlock services are estimates only and are not guaranteed. Actual processing times may vary based on carrier processing, provider workload, and other factors outside our control.</Section>
          <Section n={17} title="Service Success Rates">We publish success rate information based on historical data. Past success rates do not guarantee future results. Some devices may be ineligible for unlocking based on carrier policies or device status.</Section>
          <Section n={18} title="No Guarantee of Unlock Success">GSM World does not guarantee that every submitted unlock request will be successful. Certain devices with specific statuses (e.g., barred, reported stolen, blacklisted) may not be eligible for unlocking.</Section>
          <Section n={19} title="User Responsibilities for Service Requests">You are responsible for providing accurate device information (IMEI, serial number, model) when submitting orders. Inaccurate information may result in failed orders, and refunds may not be available in such cases.</Section>
          <Section n={20} title="IMEI Verification">By submitting an IMEI, you confirm that you are the lawful owner of the device or have explicit authorization from the owner to submit it for service. Submitting IMEIs of stolen or illegally obtained devices is a criminal offense.</Section>
          <Section n={21} title="Prohibited Device Submissions">You may not submit devices that are reported as stolen, lost, or otherwise flagged as illegally obtained. We cooperate fully with law enforcement in cases involving such submissions.</Section>
          <Section n={22} title="Wallet Funding">You may add funds to your GSM World wallet using supported payment methods including M-Pesa, cryptocurrency, and credit/debit card where available. All wallet credits are in US Dollars unless otherwise stated.</Section>
          <Section n={23} title="Minimum and Maximum Deposits">We may impose minimum and maximum deposit amounts at our discretion. These limits may change without notice and will be displayed at the time of the transaction.</Section>
          <Section n={24} title="Payment Processing">Payments are processed by third-party payment providers. GSM World is not responsible for delays, failures, or errors in payment processing caused by third-party providers or banking institutions.</Section>
          <Section n={25} title="Currency">All prices on the platform are displayed in US Dollars (USD) unless otherwise stated. Currency conversion for non-USD payment methods is determined at the time of transaction and may include exchange rate margins.</Section>
          <Section n={26} title="Pricing">Prices for services are displayed on the platform and are subject to change without notice. You will be charged the price displayed at the time you confirm your order.</Section>
          <Section n={27} title="Taxes">You are responsible for any applicable taxes, duties, or levies arising from your use of the Service or your purchase of services, as determined by the laws of your jurisdiction.</Section>
          <Section n={28} title="Failed Payments">If a payment fails to process, the corresponding order will not be fulfilled. You will be notified and may attempt the payment again. GSM World is not responsible for delays caused by payment failures.</Section>
          <Section n={29} title="Unauthorized Charges">If you believe an unauthorized charge has been made to your payment method, you must notify us and your payment provider immediately. We will cooperate fully in investigating the matter.</Section>
          <Section n={30} title="Chargebacks">Initiating a chargeback for a legitimate purchase without first contacting our support team is a violation of these Terms. We reserve the right to suspend accounts associated with frivolous or fraudulent chargebacks.</Section>
          <Section n={31} title="Wallet Non-Transferability">Wallet balances are non-transferable to other accounts and have no cash value outside the Service unless a refund is approved in accordance with our Refund Policy.</Section>
          <Section n={32} title="Wallet Expiry">We reserve the right to implement wallet balance expiry policies with appropriate notice. Any such policy will be communicated at least 30 days before taking effect.</Section>
          <Section n={33} title="Order Placement">Orders are placed when you confirm a service purchase and a corresponding transaction is recorded on our platform. Confirmation emails are sent as acknowledgment but do not constitute a guarantee of service completion.</Section>
          <Section n={34} title="Order Cancellation by User">Orders may be cancelled while in "Pending" status. Once an order has been submitted to a third-party provider for processing, cancellation may not be possible and refunds may be subject to our Refund Policy.</Section>
          <Section n={35} title="Order Cancellation by GSM World">We reserve the right to cancel orders that cannot be fulfilled due to provider issues, policy changes, device ineligibility, or suspected fraud. Wallet credits will be restored for cancelled orders in most cases.</Section>
          <Section n={36} title="Order Status Updates">We provide order status updates via the platform and email. You are responsible for maintaining a valid email address and for checking order status updates within the platform.</Section>
          <Section n={37} title="Completed Orders">Once an unlock code or service result has been delivered and the order marked as complete, the transaction is considered final. Claims for refund after delivery of a successful result are not accepted.</Section>
          <Section n={38} title="Order Records">Order records are maintained in your account and are accessible for the retention period described in our Privacy Policy. You should retain order confirmations and results for your own records.</Section>
          <Section n={39} title="Refund Policy — General">Refunds are available for orders that fail due to provider error or where GSM World determines the service cannot be delivered. Refunds are issued as wallet credits unless otherwise agreed.</Section>
          <Section n={40} title="Refund Policy — Non-Refundable Services">Certain services are explicitly marked as non-refundable at the time of purchase, including services with high delivery certainty or where the third-party provider has already completed the service delivery.</Section>
          <Section n={41} title="Refund Policy — Timeframe">Refund requests must be submitted within 30 days of the order date. Claims submitted after this period will not be considered unless exceptional circumstances apply at our sole discretion.</Section>
          <Section n={42} title="Refund Policy — Incorrect Information">Refunds will not be issued where an order failed due to inaccurate or incomplete information provided by the user, including incorrect IMEI numbers, device models, or carrier information.</Section>
          <Section n={43} title="Refund Policy — Process">To request a refund, contact our support team with your order ID and reason for the request. We aim to process refund requests within 5 business days of receiving complete information.</Section>
          <Section n={44} title="Reseller Program">GSM World offers a reseller program allowing approved users to purchase services at discounted rates for resale to end customers. Reseller status is granted at our sole discretion and may be revoked at any time.</Section>
          <Section n={45} title="Reseller Responsibilities">Resellers are solely responsible for their relationships with end customers, including pricing, service delivery communication, support, and compliance with applicable consumer protection laws.</Section>
          <Section n={46} title="Reseller Conduct">Resellers must not make representations about GSM World services that go beyond what is stated on our platform, nor guarantee outcomes that we ourselves do not guarantee.</Section>
          <Section n={47} title="API Access">Where we provide API access, you must use it only in accordance with our API documentation and these Terms. Unauthorized or abusive use of our API will result in immediate access revocation.</Section>
          <Section n={48} title="Intellectual Property — Ownership">All content on the GSM World platform, including but not limited to text, graphics, logos, icons, images, audio, and software, is the property of GSM World or its licensors and is protected by applicable intellectual property laws.</Section>
          <Section n={49} title="Intellectual Property — License">We grant you a limited, non-exclusive, non-transferable, revocable license to access and use the Service for your personal or business purposes in accordance with these Terms.</Section>
          <Section n={50} title="Intellectual Property — Restrictions">You may not copy, modify, distribute, sell, sublicense, or create derivative works from any part of the Service without our prior written consent.</Section>
          <Section n={51} title="Intellectual Property — User Content">By submitting content to the platform (such as feedback, reviews, or support messages), you grant us a worldwide, royalty-free license to use, reproduce, and display that content in connection with operating and improving the Service.</Section>
          <Section n={52} title="Intellectual Property — Trademarks">GSM World, its logo, and related marks are trademarks of GSM World. You may not use these marks without our prior written permission. Third-party trademarks appearing on the platform remain the property of their respective owners.</Section>
          <Section n={53} title="Prohibited Uses — Illegal Activity">You may not use the Service for any purpose that violates applicable law, including but not limited to submitting stolen devices, money laundering, or facilitating any criminal activity.</Section>
          <Section n={54} title="Prohibited Uses — Fraud and Misrepresentation">You may not use the Service to commit fraud, impersonate any person or entity, misrepresent your identity or affiliation, or otherwise deceive GSM World, other users, or third parties.</Section>
          <Section n={55} title="Prohibited Uses — System Interference">You may not attempt to hack, disrupt, degrade, or interfere with the Service, its servers, or any network connected to the Service, including through denial-of-service attacks, malware, or unauthorized data access.</Section>
          <Section n={56} title="Prohibited Uses — Scraping and Automation">You may not use automated tools, bots, spiders, or scrapers to access, monitor, or collect data from the Service without our prior written consent, except as permitted by our API terms.</Section>
          <Section n={57} title="Prohibited Uses — Reverse Engineering">You may not decompile, disassemble, reverse engineer, or otherwise attempt to derive the source code of any software comprising or operating the Service.</Section>
          <Section n={58} title="Prohibited Uses — Account Sharing">You may not share your account credentials with third parties. Each account is for the sole use of the registered user. Commercial account sharing arrangements require prior written approval from GSM World.</Section>
          <Section n={59} title="Prohibited Uses — Circumventing Restrictions">You may not use technical means to circumvent any access restrictions, geographic limitations, or other controls implemented by GSM World on the Service.</Section>
          <Section n={60} title="Prohibited Uses — Spam and Harassment">You may not use the Service to send unsolicited commercial communications, harass other users, or engage in any conduct that could reasonably be perceived as threatening, abusive, or harmful.</Section>
          <Section n={61} title="Content Standards">Any content you submit to the platform must not be illegal, defamatory, obscene, threatening, invasive of privacy, infringing of intellectual property rights, or otherwise harmful or objectionable.</Section>
          <Section n={62} title="Monitoring and Enforcement">GSM World reserves the right, but has no obligation, to monitor user activity on the platform and to remove or restrict access to content or accounts that violate these Terms at our sole discretion.</Section>
          <Section n={63} title="Reporting Violations">If you become aware of any misuse of the Service or violation of these Terms, please report it to our support team. We take all reports seriously and investigate them promptly.</Section>
          <Section n={64} title="Links to Third-Party Services">The Service may contain links to third-party websites or services. We do not endorse, control, or take responsibility for any third-party content, privacy practices, or services accessed through such links.</Section>
          <Section n={65} title="Beta Features">From time to time, we may offer access to beta features. Beta features are provided "as is" without warranty and may be discontinued at any time. Feedback you provide about beta features may be used to improve the Service.</Section>
          <Section n={66} title="Disclaimer of Warranties">The Service is provided on an "as is" and "as available" basis without any warranties, express or implied, including warranties of merchantability, fitness for a particular purpose, title, or non-infringement.</Section>
          <Section n={67} title="No Warranty of Results">We do not warrant that the Service will meet your specific requirements, that results of using the Service will be accurate or reliable, or that the quality of services obtained will meet your expectations.</Section>
          <Section n={68} title="Limitation of Liability — General">To the fullest extent permitted by applicable law, GSM World and its officers, directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service.</Section>
          <Section n={69} title="Limitation of Liability — Cap">Our total liability to you for any claims arising under these Terms shall not exceed the amount you paid to GSM World in the twelve months immediately preceding the event giving rise to the claim.</Section>
          <Section n={70} title="Limitation of Liability — Exceptions">Nothing in these Terms shall limit or exclude our liability for death or personal injury caused by our negligence, fraudulent misrepresentation, or any other liability that cannot be excluded by law.</Section>
          <Section n={71} title="Indemnification">You agree to indemnify, defend, and hold harmless GSM World and its affiliates, officers, directors, employees, and agents from any claims, liabilities, damages, losses, costs, and expenses arising from your use of the Service or your violation of these Terms.</Section>
          <Section n={72} title="Indemnification — Process">GSM World will provide prompt notice of any claim subject to indemnification. We reserve the right to assume exclusive control of the defense of any such matter, and you agree to cooperate fully.</Section>
          <Section n={73} title="Force Majeure">We are not liable for any failure to perform our obligations where such failure results from circumstances beyond our reasonable control, including natural disasters, pandemic, government actions, power failures, or internet disruptions.</Section>
          <Section n={74} title="Data Accuracy Disclaimer">We make no representations about the accuracy of IMEI data, carrier information, or device status data obtained from third-party data sources. Such information is provided for informational purposes only.</Section>
          <Section n={75} title="No Professional Advice">Nothing on the GSM World platform constitutes legal, financial, or technical professional advice. You should seek appropriate professional advice before making decisions based on information obtained from our Service.</Section>
          <Section n={76} title="Governing Law">These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which GSM World is registered, without regard to its conflict of law provisions.</Section>
          <Section n={77} title="Dispute Resolution — Informal First">Before initiating any formal dispute resolution process, you agree to contact our support team and attempt to resolve the dispute informally. Most issues can be resolved quickly through direct communication.</Section>
          <Section n={78} title="Dispute Resolution — Timeframe for Informal Resolution">We will make good faith efforts to resolve your concern within 30 days of receiving your written notice of the dispute. If not resolved, either party may proceed to formal dispute resolution.</Section>
          <Section n={79} title="Dispute Resolution — Arbitration">Any disputes that cannot be resolved informally shall be submitted to binding arbitration in accordance with applicable arbitration rules. The arbitration shall be conducted in English.</Section>
          <Section n={80} title="Dispute Resolution — Exceptions">Notwithstanding the arbitration clause, either party may seek emergency injunctive relief from a court of competent jurisdiction to protect confidential information or intellectual property rights pending arbitration.</Section>
          <Section n={81} title="Dispute Resolution — Waiver of Class Action">To the fullest extent permitted by law, you waive your right to participate as a plaintiff or class member in any class action lawsuit against GSM World related to the Service or these Terms.</Section>
          <Section n={82} title="Dispute Resolution — Jurisdiction">For disputes not subject to arbitration, you consent to the exclusive jurisdiction of the courts in the jurisdiction in which GSM World is registered.</Section>
          <Section n={83} title="Limitation of Actions">Any claim arising from or related to these Terms or the Service must be brought within one year of the date on which the cause of action accrued, or it is permanently barred.</Section>
          <Section n={84} title="Modifications to Terms">We reserve the right to modify these Terms at any time. We will provide notice of material changes by email or through a prominent notice on the platform. Continued use after changes take effect constitutes acceptance.</Section>
          <Section n={85} title="Notification of Changes">We will notify you of material changes to these Terms at least 14 days before they take effect, except for changes required by law or to address security issues, which may take effect immediately.</Section>
          <Section n={86} title="Severability">If any provision of these Terms is found to be unenforceable or invalid under applicable law, that provision shall be limited or eliminated to the minimum extent necessary while the remaining Terms remain in full force and effect.</Section>
          <Section n={87} title="Waiver">Our failure to enforce any right or provision of these Terms shall not constitute a waiver of that right or provision. A waiver of any breach on one occasion does not waive future breaches of the same or any other provision.</Section>
          <Section n={88} title="Entire Agreement">These Terms, together with our Privacy Policy and any other policies incorporated by reference, constitute the entire agreement between you and GSM World with respect to the Service, superseding all prior agreements.</Section>
          <Section n={89} title="Assignment">You may not assign or transfer these Terms or any rights under them without our prior written consent. We may assign these Terms without restriction. Any prohibited assignment is null and void.</Section>
          <Section n={90} title="No Partnership or Agency">These Terms do not create any partnership, joint venture, employment, franchise, or agency relationship between you and GSM World. You do not have authority to bind GSM World in any way.</Section>
          <Section n={91} title="Third-Party Beneficiaries">These Terms do not confer any rights or benefits on any third party. Only you and GSM World have rights and obligations under these Terms.</Section>
          <Section n={92} title="Notices">Notices from GSM World to you will be delivered to the email address registered with your account. Notices from you to GSM World must be sent to our official support email address.</Section>
          <Section n={93} title="Language">These Terms are written in English. Any translation provided is for convenience only. In the event of any conflict between versions, the English version shall prevail.</Section>
          <Section n={94} title="Headings">Section headings are included for convenience only and do not affect the interpretation of these Terms. They should not be construed as limiting the scope of any provision.</Section>
          <Section n={95} title="Electronic Acceptance">By clicking "I agree," creating an account, or using the Service, you electronically accept these Terms. This electronic acceptance has the same legal force and effect as a written, physical signature.</Section>
          <Section n={96} title="Accessibility">We strive to make our platform accessible to users with disabilities. If you encounter accessibility barriers, please contact our support team and we will make reasonable efforts to assist you.</Section>
          <Section n={97} title="Feedback">If you provide feedback, suggestions, or ideas about the Service, you grant us a perpetual, irrevocable, worldwide, royalty-free license to use and incorporate that feedback without compensation or attribution to you.</Section>
          <Section n={98} title="Digital Services Compliance">Where applicable, we comply with digital services regulations including the EU Digital Services Act and equivalent legislation, including maintaining transparency in our content moderation practices.</Section>
          <Section n={99} title="Anti-Money Laundering">We are committed to compliance with applicable anti-money laundering laws. We may request additional verification for large transactions and will report suspicious activity to relevant authorities as required by law.</Section>
          <Section n={100} title="Sanctions Compliance">GSM World does not provide services to individuals or entities that are subject to applicable sanctions programs. We reserve the right to refuse or reverse transactions where sanctions compliance requires it.</Section>
          <Section n={101} title="Export Controls">You represent that you are not located in a country subject to applicable export restrictions and that you are not a person or entity to whom such services are prohibited under applicable export control laws.</Section>
          <Section n={102} title="Consumer Rights">Nothing in these Terms is intended to exclude or limit any statutory consumer rights that cannot be legally excluded or limited under applicable consumer protection law in your jurisdiction.</Section>
          <Section n={103} title="Complaints Procedure">If you are dissatisfied with any aspect of the Service, please contact our support team with full details of your complaint. We will acknowledge your complaint within 2 business days and aim to resolve it within 10 business days.</Section>
          <Section n={104} title="Escalation">If your complaint is not resolved to your satisfaction through our standard support process, you may request escalation to our management team by explicitly stating your wish to escalate in your support correspondence.</Section>
          <Section n={105} title="Survival">Provisions of these Terms that by their nature should survive termination shall survive, including ownership provisions, warranty disclaimers, indemnity obligations, limitations of liability, and dispute resolution provisions.</Section>
          <Section n={106} title="Acknowledgment">By using the Service, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions, and that you have reviewed our Privacy Policy and agree to its terms.</Section>
        </div>
      </div>
    </div>
  );
}
