kind = "api"
  previewPath = "/__api-legacy-1"
  title = "API Server (legacy)"
  version = "1.0.0"
  id = "3B4_FFSkEVBkAeYMFRJ2e"

  [[services]]
  localPort = 8080
  name = "API Server"
  paths = ["/__api-legacy-1"]

  [services.development]
  run = "pnpm --filter @workspace/api-server run dev"
  